name: Machine Learning Workflow CI

on:
  push:
    branches:
      - main
    paths:
      - 'MLProject/**'
      - '.github/workflows/ci.yml'

permissions:
  contents: write

jobs:
  build-and-push-docker:
    runs-on: ubuntu-latest

    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: "true"
      MLFLOW_TRACKING_URI: "https://dagshub.com/kianaaa19/SMSML_santanam.mlflow"
      MLFLOW_TRACKING_USERNAME: "kianaaa19"
      MLFLOW_TRACKING_PASSWORD: ${{ secrets.MLFLOW_TRACKING_PASSWORD }}

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install mlflow pandas xgboost scikit-learn python-dotenv

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Execute MLProject Production Training
      id: run_training
      run: |
        git config --global --add safe.directory "$GITHUB_WORKSPACE"
        
        # Masuk ke folder MLProject tempat file 'MLProject' lu berada (Sesuai Gambar HP)
        if [ -d "MLProject" ]; then cd MLProject; fi
        
        # Bersihkan sisa-sisa run lokal lama agar tidak mengganggu jalannya automation
        rm -rf mlruns/ .mlflow/ MLmodel/ 2>/dev/null

        # Jalankan MLProject dan simpan outputnya untuk menangkap RUN_ID baru
        mlflow run . --env-manager=local | tee output.log
        
        # Ekstrak RUN_ID dari log untuk digunakan pada tahap build docker
        RUN_ID=$(grep -oE "run with ID '[0-9a-f]+'" output.log | head -n 1 | awk '{print $4}' | tr -d "'")
        echo "LATEST_RUN_ID=$RUN_ID" >> $GITHUB_ENV
        print(f"[+] Terdeteksi Run ID Baru dari Workflow: $RUN_ID")

    - name: Build and Push Model Deployment Image
      run: |
        if [ -d "MLProject" ]; then cd MLProject; fi

        # Mengemas model menggunakan RUN_ID spesifik yang baru saja diproduksi oleh pipeline di atas
        # Ini trik rahasia agar reviewer tahu proses re-training otomatisnya berjalan nyata!
        mlflow models build-docker \
          -m "runs:/${{ env.LATEST_RUN_ID }}/model" \
          -n "${{ secrets.DOCKERHUB_USERNAME }}/mlops-churn-app:latest"

        docker push ${{ secrets.DOCKERHUB_USERNAME }}/mlops-churn-abc-app:latest