name: Machine Learning Workflow CI

on:
  push:
    branches:
      - main
    paths:
      - 'MLProject/**'
      - '.github/workflows/ci.yml'

permissions:
  contents: write

jobs:
  build-and-push-docker:
    runs-on: ubuntu-latest

    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: "true"
      MLFLOW_TRACKING_URI: "https://dagshub.com/kianaaa19/SMSML_santanam.mlflow"
      MLFLOW_TRACKING_USERNAME: "kianaaa19"
      MLFLOW_TRACKING_PASSWORD: ${{ secrets.MLFLOW_TRACKING_PASSWORD }}

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install mlflow pandas xgboost scikit-learn python-dotenv

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Execute MLProject Production Training
      run: |
        git config --global --add safe.directory "$GITHUB_WORKSPACE"
        git checkout main || git checkout -b main

        if [ -d "MLProject" ]; then cd MLProject; fi

        # JALAN KELUAR UTAMA: Suntikkan --tracking-uri secara langsung di perintah CLI
        # Ini memaksa mlflow run murni berkomunikasi dengan REST API DagsHub tanpa menyentuh file_store lokal!
        mlflow run . --env-manager=local --tracking-uri "$MLFLOW_TRACKING_URI"

    - name: Build and Push Model Deployment Image
      run: |
        if [ -d "MLProject" ]; then cd MLProject; fi

        mlflow models build-docker \
          -m "models:/Bank_Churn_Model_Santanam/latest" \
          -n "${{ secrets.DOCKERHUB_USERNAME }}/mlops-churn-app:latest"

        docker push ${{ secrets.DOCKERHUB_USERNAME }}/mlops-churn-abc-app:latest